[package]
name = "wallpaper"
version = "0.2.0"
edition = "2021"

[features]
download = [ "dep:reqwest" ]

[dependencies]
winapi = { version = "0.3.9", features = [ "winuser", "winreg"] }
reqwest = { version = "0.11.18", features = [ "blocking" ], optional = true }