[package]
name = "wallpaper"
version = "0.2.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = [ "winuser", "libloaderapi", "winreg", "wincon" ] }
reqwest = { version = "0.11.18", features = [ "blocking" ] }